---
global:
  indexerConfig:
    enabled: true
    esServers: ["<your elasticsearch url>"]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner

jobs:
  - name: api-intensive-create
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: true
    namespace: api-intensive
    podWait: false
    cleanup: true
    jobPause: 1m
    waitFor: []
    waitWhenFinished: true
    objects:
      - objectTemplate: api-intensive/templates/deployment.yaml
        replicas: 2
      - objectTemplate: api-intensive/templates/configmap.yaml
        replicas: 2
      - objectTemplate: api-intensive/templates/secret.yaml
        replicas: 10
      - objectTemplate: api-intensive/templates/service.yaml
        replicas: 10

  - name: api-intensive-patch
    jobType: patch
    jobIterations: 1
    qps: 2
    burst: 2
    objects:
      - kind: Deployment
        objectTemplate: api-intensive/templates/deployment_patch_add_label.json
        labelSelector: {kube-burner-job: api-intensive-create}
        patchType: "application/json-patch+json"
        apiVersion: apps/v1
      - kind: Deployment
        objectTemplate: api-intensive/templates/deployment_patch_add_pod_2.yaml
        labelSelector: {kube-burner-job: api-intensive-create}
        patchType: "application/apply-patch+yaml"
        apiVersion: apps/v1
      - kind: Deployment
        objectTemplate: api-intensive/templates/deployment_patch_add_label.yaml
        labelSelector: {kube-burner-job: api-intensive-create}
        patchType: "application/strategic-merge-patch+json"
        apiVersion: apps/v1

  - name: api-intensive-delete
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Deployment
        labelSelector: {kube-burner-job: api-intensive-create}
        apiVersion: apps/v1

  - name: api-intensive-delete-pods
    qps: 10
    burst: 10
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Pod
        labelSelector: {kube-burner-job: api-intensive-create}

  - name: api-intensive-delete-services
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Service
        labelSelector: {kube-burner-job: api-intensive-create}

  - name: api-intensive-delete-configmaps-secrets
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: ConfigMap
        labelSelector: {kube-burner-job: api-intensive-create}
      - kind: Secret
        labelSelector: {kube-burner-job: api-intensive-create}

  - name: api-intensive-delete-namespaces
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: Namespace
        labelSelector: {kube-burner-job: api-intensive-create}

# Openshift SDN testing

  - name: sdn-intensive-network-policy
    jobIterations: 1
    qps: 2
    burst: 2
    namespacedIterations: false
    namespace: sdn-intensive
    waitWhenFinished: false
    podWait: false
    preLoadImages: true
    preLoadPeriod: 2m
    objects:

      - objectTemplate: kubelet-density-cni-networkpolicy/templates/deny-all.yml
        replicas: 1

  - name: sdn-intensive
    jobIterations: 1
    qps: 2
    burst: 2
    namespacedIterations: false
    namespace: sdn-intensive
    waitWhenFinished: false
    podWait: false
    preLoadImages: true
    preLoadPeriod: 2m
    objects:

      - objectTemplate: kubelet-density-cni-networkpolicy/templates/webserver-deployment.yml
        replicas: 2

      - objectTemplate: kubelet-density-cni-networkpolicy/templates/webserver-service.yml
        replicas: 1

      - objectTemplate: kubelet-density-cni-networkpolicy/templates/allow-http.yml
        replicas: 1

      - objectTemplate: kubelet-density-cni-networkpolicy/templates/curl-deployment.yml
        replicas: 2

  - name: sdn-intensive-delete
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Deployment
        labelSelector: {kube-burner-job: sdn-intensive}
        apiVersion: apps/v1

  - name: sdn-intensive-delete-pods
    qps: 10
    burst: 10
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Pod
        labelSelector: {kube-burner-job: sdn-intensive}


  - name: sdn-intensive-delete-services
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Service
        labelSelector: {kube-burner-job: sdn-intensive}

  - name: sdn-intensive-delete-namespaces
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: Namespace
        labelSelector: {kube-burner-job: sdn-intensive-network-policy}

# Openshift testing        
  
  - name: cluster-intensive
    jobIterations: 1
    qps: 2
    burst: 2
    namespacedIterations: true
    namespace: cluster-intensive
    podWait: false
    waitFor: []
    waitWhenFinished: true
    objects:

      - objectTemplate: cluster-density/templates/imagestream.yml
        replicas: 3
        inputVars:
          prefix: cluster-density-src
          image: quay.io/cloud-bulldozer/ubi8-go-toolset

      - objectTemplate: cluster-density/templates/imagestream.yml
        replicas: 3
        inputVars:
          prefix: cluster-density-dst
          image: quay.io/cloud-bulldozer/ubi8-go-toolset

      - objectTemplate: cluster-density/templates/buildconfig.yml
        replicas: 1
        inputVars:
          from: cluster-density-src
          to: cluster-density-dst
          gitUri: https://github.com/cloud-bulldozer/hello-openshift.git

      - objectTemplate: cluster-density/templates/imagestream.yml
        replicas: 3
        inputVars:
          prefix: cluster-density

      - objectTemplate: cluster-density/templates/build.yml
        replicas: 1
        inputVars:
          prefix: cluster-density

      - objectTemplate: cluster-density/templates/deployment.yml
        replicas: 2
        inputVars:
          podReplicas: 2
          name: deployment-2pod
          envVar: 55d897a9c68ea8a48e59f5ec9cf40aa7ffbdfd33e40bf71ee0ffdba1611518586015791965693165b030b20af4d0979a83d098fcf289e9e9fcbb170df5b144314f3d8d5c0755e0415ed5f8ec53a20f0ac8344e719e0993b3ddecd1d6e7b5f9a4b4cf78c9b9a6f328d754d955d897a9c68ea8a48e59f5ec9cf40aa7ffbdfd33e40bf71ee0ffdba1611518586015791965693165b030b20af4d0979a83d098fcf289e9e9fcbb170df5b144314f3d8d5c0755e0415ed5f8ec53a20f0ac8344e719e0993b3ddecd1d6e7b5f9a4b4cf78c9b9a6f328d754d92857528fe63427c66d5427cc3b61a10a86d5970c4315ced8f0584e1aabc9a696b2414df6268413cb0cdf8828d4fdd2504121e66309b19544325466a8cb2c599307f4ff76eeb64254b81c3fe4969759ff8fd811851d2ff4784c4959eb9af44eda26feb7ede29029c675c317fcc68fc900b52ba28b6e7af3e1d5523e0070776e406371ff6ca1b2437f9e0629b691234edbbeffbabfc305

      - objectTemplate: cluster-density/templates/service.yml
        replicas: 1
        inputVars:
          name: deployment-2pod

      - objectTemplate: cluster-density/templates/deployment.yml
        replicas: 2
        inputVars:
          podReplicas: 2
          name: deployment-1pod
          envVar: 27a63fb116963f0fa41101718885c9f9a1ad0252edf1be22248d0e055eebaba918c1a909d6ea594901042c182960449ffea636f4c266cfbbd0fbabc819ca86370a9b92d7bf28216e03e2f67785afcdc413f09f339bd2fd8fee0479126a64a74021478b244680fe7ef629da7a873821bf44e2eff41d376130d6d9c16ad23b639179692e52bc0880367aadf2cc38f2a72501d01cd70d64d714421b9bb018546d8ba0ade9ca8f4e063ba261d44e688cdcea6353172388fd91d9daffe942e451a27a9d4775a966eb991ae4d37f919445c6d0d14e2a048a17d92de253120943c85ea95b73b696902612d2b02c1530dd8344e2c65b507cbfb820bc17bdade0a58652b2ae2857528fe63427c66d5427cc3b61a10a86d5970c4315ced8f0584e1aabc9a696b2414df6268413cb0cdf8828d4fdd2504121e66309b19544325466a8cb2c599307f4ff76eeb64254b81c3fe4969759ff8fd811851d2ff4784c4959eb9af44eda26feb7ede29029c675c317fcc68fc900b52ba28b6e7af3e1d5523e0070776e406371ff6ca1b2437f9e0629b691234edbbeffbabfc305

      - objectTemplate: cluster-density/templates/service.yml
        replicas: 2
        inputVars:
          name: deployment-1pod

      - objectTemplate: cluster-density/templates/route.yml
        replicas: 10
        inputVars:
          name: deployment-2pod

      - objectTemplate: cluster-density/templates/route.yml
        replicas: 10
        inputVars:
          name: deployment-1pod

      - objectTemplate: cluster-density/templates/secret.yml
        replicas: 10

      - objectTemplate: cluster-density/templates/configmap.yml
        replicas: 10

  - name: cluster-intensive-delete
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Deployment
        labelSelector: {kube-burner-job: cluster-intensive}
        apiVersion: apps/v1

  - name: cluster-intensive-delete-pod
    qps: 10
    burst: 10
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Pod
        labelSelector: {kube-burner-job: cluster-intensive}

  - name: cluster-intensive-delete-services
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Service
        labelSelector: {kube-burner-job: cluster-intensive}

  - name: cluster-intensive-delete-configmaps-secrets
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: ConfigMap
        labelSelector: {kube-burner-job: cluster-intensive}
      - kind: Secret
        labelSelector: {kube-burner-job: cluster-intensive}

  - name: cluster-intensive-delete-namespaces
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: Namespace
        labelSelector: {kube-burner-job: cluster-intensive}
